### ISSUE TITLE
Write a test for class BankViewSet using get method to verify bank details

### ISSUE THREAD

**Issue by pgeorge2** [thenewboston-developers/Bank#107]
Write a test called `test_banks_detail` to verify the bank detail and 200 status code. Also, verify the 404 status for invalid bank details by passing any random node_identifier.

Hint: In this test, we need to verify the bank details using node_identifier. we need to prepare a test for url /banks/<node_identifier>.
For example, if we have a bank with d5356888dc9303e44ce52b1e06c3165a7759b9df1e6a6dfbd33ee1c3df1ab4d1 node identifier, then use bank/d5356888dc9303e44ce52b1e06c3165a7759b9df1e6a6dfbd33ee1c3df1ab4d1 and verify the response with 200 status.
node_identifier
To verify 404 status of data not found, pass any random node_identifier and test it.

**Comment by DucPhamTV** [comment]
I take this.
