### ISSUE TITLE
Write a test to validate unique constraint of block and validator together

### ISSUE THREAD

**Issue by pgeorge2** [thenewboston-developers/Bank#108]
Write a test called `test_confirmation_block_post_400_unique_recipients`. Pass the dummy data and verify 400 status code along with the unique constraint error message. Refer `ConfirmationBlockViewSet` view and `ConfirmationBlock` model.

Hint: Refer below link for reference.
[https://github.com/thenewboston-developers/Bank/blob/14df0677f536e60518363b74c172bee0e21353d9/v1/blocks/tests/block.py#L46](https://github.com/thenewboston-developers/Bank/blob/14df0677f536e60518363b74c172bee0e21353d9/v1/blocks/tests/block.py#L46)

**Comment by DucPhamTV** [comment]
I take this.
