### ISSUE TITLE
Write a test to validate value of account number and trust in accounts

### ISSUE THREAD

**Issue by pgeorge2** [thenewboston-developers/Bank#121]
Write a test called `test_bank_account_number_trust` pass the account number longer than expected length and validate the 400 status error. Also, validate trust value of a bank and it must reside beween 0 to 100. Pass trust value as either negative or more than 100 and validate 400 status code.

Hint: Length of the account number should be 64 characters.

**Comment by DucPhamTV** [comment]
> pass the account number longer than expected length and validate the 400 status error.

if account number is longer than 64 chars, the 404 status error will be returned. So I think only the tests about trust level are needed.
