### ISSUE TITLE
OpenAPI (Swagger) for API

### ISSUE THREAD

**Issue by vosi** [thenewboston-developers/Bank#59]

**Comment by sno2** [comment]
This is a **lot** of work for only 5,000 coins if we were to strictly follow this spec.

**Comment by vosi** [comment]
@sno2 no, its a quite simple task, there is no need to apply an extended description etc, it's about installing and setting an appropriate django drf plugin

**Comment by adewolejosh** [comment]
Hi, My Account Number is 074373d18830363452ea5bb3b17ad348adbad66526dc3962ab048beb7945f8e9
