### ISSUE TITLE
Crawl for Banks & Validators

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Bank#61]
- An authenticated Bank or Validator will have the option to crawl their own server to make sure the servers data is up to date. 
- There will be 3 possible "Crawl" statuses.
- 1. **Not Crawling** status w/ Crawl button
- 2. **Crawling status** w/ Request Stop button
- 3. **Stop Request** status and no button
- Crawl Status UI will be a block above the Bank's Network ID & Acc#. 
- Statuses use the colors Sail Red/Green 500

In the near future, we are going to include 'Clean', but that will be for a later ticket. 

https://www.figma.com/file/ObSUx1rum1MIeZkFT3XIn1/Bank-User?node-id=809%3A0

**Comment by buckyroberts** [comment]
Moved to https://github.com/thenewboston-developers/Account-Manager/issues/356
