### ISSUE TITLE
Bank OVERVIEW UI update 

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Bank#63]
We are giving more content hierarchy to the way the Banks OVERVIEW information is read. Please view the mocks and include the blocks listed. 

**Blocks listed**
- Tx Fee Block (independent block)
- Confirmation Services (independent block)
- IP Address, Port, Protocol, Version, Node Type
- Bank Network ID & Bank Account Number (Include secondary button 'Add Signing Keys (For DEVOPS)

https://www.figma.com/file/ObSUx1rum1MIeZkFT3XIn1/Bank-User?node-id=837%3A4160

**Comment by buckyroberts** [comment]
Moved to https://github.com/thenewboston-developers/Account-Manager/issues/354
