### ISSUE TITLE
Increase CodeBuild Tier

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Bank#88]
<img width="739" alt="Screen Shot 2020-11-09 at 4 35 18 PM" src="https://user-images.githubusercontent.com/8547538/98617512-0481b880-22b4-11eb-94e3-cab7ce6c9d5b.png">

**Comment by vosi** [comment]
It's not possible to increase a free tier, and there is nothing to do, it's just an indication that you are out of free minutes. rest will be billed. @buckyroberts
