### ISSUE TITLE
Bank API access is currently open for all

### ISSUE THREAD

**Issue by mahihossain** [thenewboston-developers/Bank#90]
**Bug Description**
Currently, anyone can browse and see the details of accounts, transactions, and many more since the API access point is not hidden. 

**Steps to Reproduce**
1. Go to 'http://143.110.137.54/'
2. Click on any links shown below.
3. Scroll down to see all the details.

**Expected behavior**
It should be hidden from public access.

**Actual behavior**
Now anyone can access it.

**Screenshots/Recordings**

![Untitled](https://user-images.githubusercontent.com/23065512/99141508-2f825880-2676-11eb-8e98-0809bfedde8e.png)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome

**Account Number**
def3963e9afcdb0e7e9c00077bea51bd7233540b41eb78a384c2567986b4edf3

**Comment by sno2** [comment]
All of this data should be public.

**Comment by buckyroberts** [comment]
Yep, like @sno2 said this data is publicly available.
