### ISSUE TITLE
"bank with that node identifier already exists"

### ISSUE THREAD

**Issue by Ahmad138** [thenewboston-developers/Bank#94]
**Bug Description**
while setting up the bank, under the section of setting a primary validator, I get a status 400 error 
```
Unable to connect
status_code:400 - {"node_identifier":["Bank with that node identifier already exists"]}
```

**Steps to Reproduce**
1. After getting to the stage of "Connect to the primary validator:" for bank setup
2. after running this code "python3 manage.py set_primary_validator"
3. And setting the public Ip to "54.183.17.224", http, 80 and trust:100
4. Then the error pops up

**Expected behavior**
It should be successful as indicated from the tutorial video on youtube channel

**Actual behavior**
But instead, I get this error
```
Unable to connect
status_code:400 - {"node_identifier":["Bank with that node identifier already exists"]}
```

**Screenshots/Recordings**
see linked image
[Error Screenshot](https://ibb.co/nDCtTHK)

**OS and Browser**
 - OS: Ubuntu 20 server

**Additional context**

**Account Number**
Your account number where the reward points for this bug bounty will be sent (pending review and approval).
15f80bd89745bafb055bba52d886f252dcab9fb3b73a382ed7adc498042fa34b

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by DucPhamTV** [comment]
I guess you follow this guide: https://thenewboston.com/deployment-guide/bank. Did you replace NETWORK_SIGNING_KEY by your own key? It is the private key of `node_identifier`.

**Comment by Ahmad138** [comment]
I didn't. It didn't say anything about replacing the NETWORK_SIGNING_KEY and assumed it's a default value

**Comment by DucPhamTV** [comment]
Actually this is just example NETWORK_SIGNING_KEY, You should create a pair of key by Account Manager and use it when following the guide.
Fortunately, there is a detail video tutorial to deploy a bank node. https://www.youtube.com/watch?v=uO-XFbOSSiA. Hope this helps

**Comment by Ahmad138** [comment]
Cheers, greatly appreciated. it will be helpful for those following the documentation to know that actually to differentiate defaults values and unique values

**Comment by Ahmad138** [comment]
problem solved, checkout the youtube tutorial for detailed setup
