### ISSUE TITLE
Fix Flake8 Issues for Bank

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Bank#96]
Fix all issues give when running `flake8 .` and then uncomment https://github.com/thenewboston-developers/Bank/blob/master/.github/workflows/pr.yml#L45

<img width="1072" alt="Screen Shot 2020-11-21 at 2 28 56 PM" src="https://user-images.githubusercontent.com/8547538/99888991-fdd53880-2c05-11eb-8b47-42b4144fd60f.png">

**Comment by vosi** [comment]
+ uncomment https://github.com/thenewboston-developers/Bank/blob/master/.github/workflows/pr.yml#L45

**Comment by makaramkd** [comment]
I would like to try this if its not assigned.

**Comment by milesgranger** [comment]
Is there a way to prevent this from happening after it's fixed? Seems the repo isn't set up with CI/CD and almost no tests to speak of. Should this not also include setting that up so we don't re-raise this issue?
